# Auto-generated behavior script
# behavior_type: magnetic
# Generated by palatial-sim-gen-physics behavior_script_generator
# DO NOT EDIT — re-run physics_processor.py to regenerate

"""
Boiler plate for all magnetic effect objects
sourced from controller.py from :
large_furniture/cupboard/ (2 items)
major_appliances/dishwasher/ (4 items)
major_appliances/refrigerator/fridge/ (4 items)
major_appliances/refrigerator/refrigerator/ (4 items)
"""

import math
import numpy as np
import omni.usd
import torch
from omni.kit.scripting import BehaviorScript
from isaacsim.core.prims import Articulation
from isaacsim.core.utils.types import ArticulationActions
from pxr import UsdPhysics


def find_prim_path_by_name(prim_name: str, root_path: str = "/") -> str:
    """Recursively find the full path by Prim name.

    Prefers a prim that has ArticulationRootAPI applied so the PhysX tensors
    plugin receives a proper rigid-body articulation root rather than a plain
    Xform ancestor that happens to share the same name token.
    """
    stage = omni.usd.get_context().get_stage()
    prim = stage.GetPrimAtPath(root_path)

    def _find_all(current, results):
        if current.GetName() == prim_name:
            results.append(current.GetPath().pathString)
        for child in current.GetChildren():
            _find_all(child, results)

    results = []
    _find_all(prim, results)
    if not results:
        raise RuntimeError(f"Prim '{prim_name}' not found under {root_path}")

    for path in results:
        if stage.GetPrimAtPath(path).HasAPI(UsdPhysics.ArticulationRootAPI):
            return path
    return results[0]

class MagneticDoorControl(BehaviorScript):
    def on_init(self):
        articulation_root_path = None
        # --- PARAMS_START ---
        self.possible_asset_root_names = ['textured_mesh_6a741da85d45b936d647e876']
        self.joint_names = ['joint_part_2__part_0', 'joint_part_2__part_1']
        self.rest_pose_state = 'open'
        self.closed_limit_side = ['min', 'max']
        self.joint_threshold = 0.3
        self.decay_rate = 3.0
        self.max_stiffness = 20.0
        self.min_stiffness = 2.0
# --- PARAMS_END ---

        for root_name in self.possible_asset_root_names:
            try:
                articulation_root_path = find_prim_path_by_name(root_name)
                print(f"Found articulation root: {articulation_root_path}")
                break
            except RuntimeError:
                continue

        if articulation_root_path is None:
            raise RuntimeError(f"Could not find articulation root with names: {self.possible_asset_root_names}")

        self.articulation_root_path = articulation_root_path
        self.art = None
        self.initialized = False
        self.joint_indices = None
        self.joint_limits = None
        self.joint_limit_diffs = None
        self.closed_limit_sides = None
        self.use_torch = None
        self.joints_info = {}
        stage = omni.usd.get_context().get_stage()
        for joint_name in self.joint_names:
            joint_prim_path = find_prim_path_by_name(joint_name)
            joint_prim_obj = stage.GetPrimAtPath(joint_prim_path)
            joint = UsdPhysics.RevoluteJoint(joint_prim_obj)
            self.joints_info[joint_name] = {
                'prim': joint,
                'lower_limit': joint.GetLowerLimitAttr().Get(),
                'upper_limit': joint.GetUpperLimitAttr().Get()
            }

    def on_play(self):
        self._initialize_articulation()

    def on_stop(self):
        pass

    def on_update(self, current_time: float, delta_time: float):
        if delta_time <= 0:
            return
        if not self.initialized:
            self._initialize_articulation()
            if not self.initialized:
                return
        self.apply_behavior()

    def apply_behavior(self):
        if not self.initialized or self.art is None:
            return
        try:
            self.damping_stiffness_change()
            self.target_pose_control()
        except AttributeError:
            print("[MagneticDoorControl] Physics view invalidated, will re-initialize next frame.")
            self.initialized = False
            self.art = None

    # initialize articulation
    def _initialize_articulation(self):
        if self.initialized:
            return
        try:
            self.art = Articulation(self.articulation_root_path)
            self.art.initialize()
            self.use_torch = isinstance(self.art.get_joint_positions(), torch.Tensor)
            self.joint_indices = [self.art.get_dof_index(name) for name in self.joint_names]
            dof_limits = self.art.get_dof_limits().squeeze()
            self.joint_limits = [{
                "lower": dof_limits[idx, 0],
                "upper": dof_limits[idx, 1]
            } for idx in self.joint_indices]
            self.joint_limit_diffs = [
                abs(lim["upper"] - lim["lower"]) for lim in self.joint_limits]
            self.closed_limit_sides = [
                self._resolve_closed_limit_side(i) for i in range(len(self.joint_names))
            ]
            self.initialized = True
        except AttributeError as e:
            print(f"Physics not ready yet, will retry: {e}")
            return

    # get scalar value
    def _get_scalar_value(self, value):
        if isinstance(value, torch.Tensor):
            return value.item()
        elif hasattr(value, 'item'):
            return value.item()
        else:
            return float(value)

    def _get_joint_setting(self, setting, joint_idx):
        if isinstance(setting, (list, tuple)):
            return setting[joint_idx]
        return setting

    def _resolve_closed_limit_side(self, joint_idx):
        """Determine which limit ("min" or "max") is the closed/latched position.

        Uses closed_limit_side if explicitly set; otherwise infers from the
        limits and rest_pose_state.  The limit closest to 0 is treated as the
        neutral/flush position (mesh default = 0 deg).

        - rest_pose="open"   → neutral limit is OPEN side  → closed is opposite
        - rest_pose="closed" or None → neutral limit IS the closed side
        """
        configured = self._get_joint_setting(self.closed_limit_side, joint_idx)
        if configured in ("min", "max"):
            return configured

        lower = self._get_scalar_value(self.joint_limits[joint_idx]["lower"])
        upper = self._get_scalar_value(self.joint_limits[joint_idx]["upper"])
        neutral_side = "min" if abs(lower) <= abs(upper) else "max"

        rest_pose = self._get_joint_setting(self.rest_pose_state, joint_idx)
        if rest_pose == "open":
            return "max" if neutral_side == "min" else "min"
        return neutral_side

    """
    calculate stiffness and damping :
    stiffness = max_stiffness * exp(-decay_rate * dist_from_closed)
    dist_from_closed is measured from the closed limit (resolved via rest_pose_state).
    once dist_from_closed crosses threshold_frac * range, clamp to min_stiffness.
    """
    def calculate_stiffness(self, joint_state, joint_idx):
        joint_state_scalar = self._get_scalar_value(joint_state)
        threshold_frac = float(self._get_joint_setting(self.joint_threshold, joint_idx))
        lower = self._get_scalar_value(self.joint_limits[joint_idx]["lower"])
        upper = self._get_scalar_value(self.joint_limits[joint_idx]["upper"])
        closed_rad = lower if self.closed_limit_sides[joint_idx] == "min" else upper
        range_rad = abs(upper - lower)
        dist_from_closed = abs(joint_state_scalar - closed_rad)
        threshold_dist = threshold_frac * range_rad
        if dist_from_closed >= threshold_dist:
            return self.min_stiffness
        stiffness = self.max_stiffness * math.exp(-self.decay_rate * dist_from_closed)
        return max(self.min_stiffness, min(stiffness, self.max_stiffness))

    """
    damping stiffness change:
    For this effect - we just do K(t) = k(q_i(t)) - ie; we get the stiffness from the calculate_stiffness function and set it to the joint drive stiffness.
    """
    def damping_stiffness_change(self):
        positions = self.art.get_joint_positions().squeeze()
        stage = omni.usd.get_context().get_stage()
        for i, idx in enumerate(self.joint_indices):
            joint_name = self.joint_names[i]
            joint_drive_path = stage.GetPrimAtPath(find_prim_path_by_name(joint_name))
            joint_drive = UsdPhysics.DriveAPI.Get(joint_drive_path, "angular")
            joint_state = positions[idx]
            joint_drive.GetStiffnessAttr().Set(self.calculate_stiffness(joint_state, i))

    """
    target pose control:
    If dist_from_closed >= threshold → snap to open limit.
    Otherwise → snap to closed limit (magnetic latch).
    """
    def target_pose_control(self):
        positions = self.art.get_joint_positions().squeeze()
        targets = []
        for i, idx in enumerate(self.joint_indices):
            joint_state = positions[idx]
            joint_state_scalar = self._get_scalar_value(joint_state)
            threshold_frac = float(self._get_joint_setting(self.joint_threshold, i))
            lower = self._get_scalar_value(self.joint_limits[i]["lower"])
            upper = self._get_scalar_value(self.joint_limits[i]["upper"])
            closed_rad = lower if self.closed_limit_sides[i] == "min" else upper
            open_rad = upper if self.closed_limit_sides[i] == "min" else lower
            range_rad = abs(upper - lower)
            dist_from_closed = abs(joint_state_scalar - closed_rad)
            threshold_dist = threshold_frac * range_rad
            targets.append(open_rad if dist_from_closed >= threshold_dist else closed_rad)
        if not targets:
            return
        if self.use_torch:
            device = positions.device
            targets_tensor = torch.tensor(targets, device=device)
            indices_tensor = torch.tensor(self.joint_indices, device=device, dtype=torch.long)
            action = ArticulationActions(joint_positions=targets_tensor, joint_indices=indices_tensor)
        else:
            action = ArticulationActions(targets, joint_indices=self.joint_indices)
        self.art.apply_action(action)
